### ISSUE TITLE
VPV simple does not generate target regions for some valid genes

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#89] opened 2017-11-08 18:59 UTC
If I

1. annul the constraints on GC and repetitive content by modifying the code in class viewpoints as follows:
```
    /** Minimum allowable GC content for simple approach */
    private static final double SIMPLE_APPROACH_MIN_GC=0.0;//0.25;
    /** Maximum allowable GC content for simple approach */
    private static final double SIMPLE_APPROACH_MAX_GC=1.0;//0.65;
    /** Maximum allowable repetitive content for simple approach */
    private static final double SIMPLE_APPROACH_MAX_REPEAT=1.0;//0.30;
```
2. Prepare a list that contains only the gene symbol _ARHGEF40_

3. Import this list to VPV

then VPV reports a valid gene symbol

![image](https://user-images.githubusercontent.com/10495485/32568062-7c7754ba-c4bd-11e7-83be-2cbd99feee59.png)

If I accept and click on _Create Viewpoints!_ the parameter check window looks as follows.

![image](https://user-images.githubusercontent.com/10495485/32568194-d318b32c-c4bd-11e7-8519-966b58c27cfa.png)

If I click on _Continue_ the following error widow pops up.

![image](https://user-images.githubusercontent.com/10495485/32568296-12cf3108-c4be-11e7-8fbc-b30e0cb71250.png)

However, if I look at the TSS of the gene _ARHGEF40_ in the UCSC genome browser, I see that the TSS containing fragment is large enough, and that the tool _CapSequm_ generates probes for this gene.

![image](https://user-images.githubusercontent.com/10495485/32568543-d8eb696a-c4be-11e7-937b-8f2d6294ce86.png)

There are more case, e.g. _CARMIL3_ and _CIRBP_.

**Comment by hansenp** [comment] 2017-11-09 10:45
The is a more complete list of the affected genes:

CCDC106
EGR2
IL13RA2
IL16
IL20RB
IL5RA
DUSP4
IL11
ARHGEF40
FAM198B
CCND2
BRSK1
IL21R
CIRBP
IL17D
CSF1
IL32
CARMIL3
IL18BP
GATA3
FN1

**Comment by pnrobinson** [comment] 2017-11-09 11:39
For some reason, ARHGEF40 appears on the validated gene list but "disappears" from the list of viewpoints and is not one of the fragments in the list on the second tab. We need to find out where the problem is occuring.

**Comment by pnrobinson** [comment] 2017-11-09 11:40
The IL5RA gene has a fragment of 2060 nucleotides that satisfies the GC content and the repeat thresholds but does not get activated. Is there a length problem?

**Comment by pnrobinson** [comment] 2017-11-09 11:46
These are the current thresholds
    /** Minimum allowable fragment size for the simple approach */
    private static final int SIMPLE_APPROACH_MINSIZE=146;
    /** Maximim allowable fragment size for simple approach */
    private static final int SIMPLE_APPROACH_MAXSIZE=20000;
    /** Minimum allowable GC content for simple approach */
    private static final double SIMPLE_APPROACH_MIN_GC=0.25;
    /** Maximum allowable GC content for simple approach */
    private static final double SIMPLE_APPROACH_MAX_GC=0.65;
    /** Maximum allowable repetitive content for simple approach */
    private static final double SIMPLE_APPROACH_MAX_REPEAT=0.30;

The repeat content of IL5RA was about 35% so this was the problem.
We should not have a separate set of thresholds for simple especially because now they cannot be set by the GUI.

**Comment by hansenp** [comment] 2017-11-09 12:42
I annulled the constraints on GC and repetitive content (see above). The problem seems to be that no _centerSegment_ is found.

**Comment by hansenp** [comment] 2017-11-09 13:30
The bug is due to the downstream size argument I used (1500). I checked some of the cases listed above. For all cases I checked the next cutting site from the TSS in downstream direction is further away than 1500.

Maybe it is not useful to use the up and downstream size arguments for the simple approach. I think the problem is (once again) that we use the same parameters also for the initialization of the segment list. In the cases listed above the segment list only contains segments upstream of the segment that 

Maybe we should reintroduce parameters such as up and downstream _limit_. They would define the region which is initially searched for fragments. They could be set e.g. to [TSS-10000;TSS+10000].

**Comment by hansenp** [comment] 2017-12-02 01:18
Since all fragments should be included in the allowed range [TSS-sizeUp;TSS+sizeDown] this is actually not a bug. I will remove the label.

I would suggest to optimize our default settings for DpnII. I would like to change the upstream size from 1500 to 2000, but cannot find the file I would have to change. @pnrobinson: Where ist it?

In the long term we should find a way to calculate appropriate values for up and downstream sizes from the expected average size of restriction fragments that could either be hard coded or estimated. I will create a new issue for this.

**Comment by pnrobinson** [comment] 2018-05-08 19:16
I am going to close this issue and open a new related one.

**Closed by pnrobinson** 2018-05-08 19:16 UTC
