### ISSUE TITLE
VPC reports the genome to be unpacked even though this is not the case

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#140] opened 2018-03-15 09:49 UTC
If click through the setup and download, unpack and index the genome, everything works fine. But when I'm going to create the viewpoints, VPC reports the genome to be unpacked.

<img width="391" alt="screen shot 2018-03-15 at 5 45 07 am" src="https://user-images.githubusercontent.com/10495485/37455719-220f1ac0-2814-11e8-8283-2ccab0950db5.png">

**Comment by pnrobinson** [comment] 2018-03-15 10:01
ca you provide relevant lines from the log file? Do you have a hg38.fa at /Users/hansep/data/hg38/hg38.fa ?

**Comment by hansenp** [comment] 2018-03-15 10:59
The only relevant entry I can find in the log file is:

`[INFO] [03-15-2018 06:42:33] (VPVMainPresenter.java:1091) - downloadGenome to directory  /Users/hansep/data/hg38`

The file `hg38.fa` is at `/Users/hansep/data/hg38`.

**Comment by pnrobinson** [comment] 2018-05-08 19:15
I cannot reproduce this error.

**Comment by pnrobinson** [comment] 2018-05-08 19:16
Since the error report is 2 months old and there has been some refactoring that may have fixed this issue, I will close the issue but we can reopen if the error turns up again.

**Closed by pnrobinson** 2018-05-08 19:16 UTC
